services:
  couchdb-obsidian-livesync:
      container_name: obsidian-livesync #shortened name
      image: couchdb
      environment:
        - PUID=99
        - PGID=100
        - UMASK=0022
        - TZ=Asia/Kolkata
        - COUCHDB_USER=divij
        - COUCHDB_PASSWORD=1234 
      volumes:
        - ./data:/opt/couchdb/data
        - ./etc/local.d:/opt/couchdb/etc/local.d
      ports:
        - "5984:5984"
      restart: unless-stopped
      labels:
        - net.unraid.docker.webui=http://[IP]:[PORT:5984]/_utils # for some reason this does not work properly
        - net.unraid.docker.icon=https://couchdb.apache.org/image/couch@2x.png
        - net.unraid.docker.shell=bash
